name: Deploy to Ubuntu Server

on:
  push:
    branches: 
      - main

jobs:
  tests: 
    name: Tests 
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Build the Next.js app
      run: npm run build  # Runs 'next build' to build the app

    - name: Start the server
      run: npm start &
      env:
        CI: true
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Wait for Next.js to be ready
      run: npx wait-on http://localhost:3100  # Waits until the app is ready before running tests
      
    - name: Run Playwright tests
      run: npx playwright test
  deploy:
    name: Deploy to Ubuntu Server
    runs-on: ubuntu-latest
    needs: tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add server to known hosts
      run: |
        ssh-keyscan ${{ secrets.SERVER_IP }}  >> ~/.ssh/known_hosts
  
    - name: Install PM2
      run: |
        npm install pm2@latest -g

    - name: Run PM2 deploy
      run: |
        pm2 deploy production update
